### ISSUE TITLE
Dayone.py cannot be imported into main.py

### ISSUE THREAD

**Issue by dat-adi** [atvc19ec/tul-s-corp#9]
The files from one folder cannot be imported into the other folder even after adding in init.py in every folder we needed.<br>
Do we need to write something into the init.py?

**Comment by SVijayB** [comment]
In your init.py present in your 'days' folder, type this : from .dayone import *
And in your main.py, add : import days

Only one init.py should do the trick.
It's like kinda like java packages.

**Comment by dat-adi** [comment]
Ohh, thanks.
It worked.
__FINALLY__

**Comment by SVijayB** [comment]
Hahahaha, No Problem.
